pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }

        stage('Deploy'){
            steps{
                echo "Simulando un despligue a un servidos de aplicaciones"
            }
        }
    }

    post{
        always{
            echo "Siempre se ejecutara"
        }
        success{
            echo "Existo este bloque se ejecuta si el pipeline se ejecuta correctamente"
        }
        failure{
            echo "Este bloque se ejecuta si el pipeline falla"
        }
    }
}